# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c02a36f0e7b2b77a72ad9aaa18f95e07dc04bdb1da13f19e08cc52319d0e3718e293f30a9fdde3898f601c213213f6ff96c66527974dfbc83505976192c26887

test:
  secret_key_base: c1448c7920c013eeb8f8cc7046750ad90df19744c1ea641c2d26d6a1539ade204a5f5cf74f197bff52b138aeabdb6134e3b5a9639d642b06e799b8bc073448c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
